#!/usr/bin/env node

var sys = require('sys')
var exec = require('child_process').exec;
var _ = require('underscore')
var request = require('request')
var program = require('commander');
function puts(error, stdout, stderr) { sys.puts(stdout) } 

program
  .version('0.0.1')
  .option('-t, --target [target]', 'Server that you wish to delete al dbs from', '')
  .option('-w, --exclude [exclude]', 'A comma seperated list of databases to exclude', '')
  .parse(process.argv);

if (program.exclude) {
  program.exclude = program.exclude.split(',')
}
else {
  program.exclude = []
}
  
var cmd = ''

request.get({uri: program.target + '/_all_dbs', json: true}, function(error, response, body) {
  if(error) return console.log(error)
  body.forEach(function(db) {
    if (program.exclude.indexOf(db) == -1) {
      cmd += 'curl -XDELETE ' + program.target + '/' + db + ' \n'
    }
  })
  console.log(cmd)
  exec(cmd, puts)
})
