#!/usr/bin/env node

/**
 * Module dependencies.
 */

var sys = require('sys')
var exec = require('child_process').exec;
var _ = require('underscore')
var request = require('request')
var program = require('commander');
var fs = require('fs')
var replicatorInstaller = require('./includes/replicator-installer')
function puts(error, stdout, stderr) { sys.puts(stdout) } 

// Increase the ulimit so the entire directory of attachments can be uploaded
exec('launchctl limit maxfiles 10056 10056', puts)
exec('ulimit -n 10056', puts)

program
  .version('0.0.1')
  .option('-u, --url [url]', '', '')
  .parse(process.argv);

var nano = require('nano')(program.url)

var skip = ['_users', '_replicator', 'resources']

var cmd = ''

nano.db.list(function(err, body) {
  if (err) return console.log(err)
  console.log(body)
  body.forEach(function(db) {
    if (_.contains(skip, db) != true) {
      cmd += 'curl -XDELETE ' + program.url + '/' + db + ' \n'
    }
  });
  console.log(cmd)
  exec(cmd, puts)
})

