#!/usr/bin/env node

var sys = require('sys')
var exec = require('child_process').exec;
var _ = require('underscore')
var request = require('request')
var program = require('commander');
function puts(error, stdout, stderr) { sys.puts(stdout) } 

program
  .version('0.0.1')
  .option('-d, --delete [delete]', 'Delete all databases of target server')
  .option('-r, --replicate [replicate]', 'Replicate all databases from source to target')
  .option('-t, --target [target]', '', '')
  .option('-s, --source [source]', '', '')
  .option('-w, --worker [worker]', '', '')
  .option('-w, --exclude [exclude]', 'A comma seperated list of databases to exclude', '')
  .parse(process.argv);

if (program.exclude) {
  program.exclude = program.exclude.split(',')
}
else {
  program.exclude = []
}
  
var cmd = ''

request.get({uri: program.source + '/_all_dbs', json: true}, function(error, response, body) {
  if(error) return console.log(error)
  body.forEach(function(db) {
    if (program.replicate) {
      if (program.exclude.indexOf(db) == -1) {
        var doc = {
          "create_target":true, 
          "source": program.source + '/' + db, 
          "target": program.target + '/' + db
        }
        cmd += 'curl -XPOST -H "Content-Type: application/json" ' + program.worker + '/_replicator -d \'' + JSON.stringify(doc) + '\' & \n'
      }
    }
    if (program.delete) {
      body.forEach(function(db) {
        if (program.exclude.indexOf(db) == -1) {
          cmd += 'curl -XDELETE ' + program.target + '/' + db + ' \n'
        }
      })
    }
  })
  console.log(cmd)
  //exec(cmd, puts)
})
